[build]
builder = "NIXPACKS"
buildCommand = "pnpm install --frozen-lockfile=false && pnpm run build"

[deploy]
startCommand = "pnpm run start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[environments.production.variables]
NODE_ENV = "production"
PORT = "8080"
