import { storage } from "./storage";
import { hashPassword } from "./auth";
import { db } from "@workspace/db";
import { users } from "@workspace/db";

export async function seedDatabase() {
  const existingUsers = await storage.getAllUsers();
  if (existingUsers.length > 0) return;

  const admin = await storage.createUser({
    name: "Admin",
    email: "admin@mirhanestate.com",
    password: hashPassword("admin123"),
    role: "admin",
  });

  const agentUser1 = await storage.createUser({
    name: "Ahmet Yılmaz",
    email: "ahmet@mirhanestate.com",
    password: hashPassword("agent123"),
    role: "agent",
  });

  const agentUser2 = await storage.createUser({
    name: "Elif Kaya",
    email: "elif@mirhanestate.com",
    password: hashPassword("agent123"),
    role: "agent",
  });

  const agent1 = await storage.createAgent({
    userId: agentUser1.id,
    companyName: "Mirhan Gayrimenkul",
    phone: "+90 549 449 23 36",
    description: "15 yıllık tecrübesiyle İstanbul'da emlak danışmanlığı yapmaktadır.",
  });

  const agent2 = await storage.createAgent({
    userId: agentUser2.id,
    companyName: "Mirhan Gayrimenkul",
    phone: "+90 549 449 23 36",
    description: "Beşiktaş, Kadıköy ve Sarıyer bölgelerinde lüks konut satışında uzmanlaşmıştır.",
  });

  const propertyData = [
    {
      title: "Kadıköy Moda'da Deniz Manzaralı 3+1 Daire",
      description: "Kadıköy Moda Mahallesi'nde, Marmara deniz manzaralı, yeni tadilatlı, geniş ve aydınlık 3+1 daire. Metro ve vapur iskelesine 5 dakika yürüme mesafesinde. Açık mutfak, banyo ve ebeveyn banyosu mevcuttur. Site içerisinde otopark ve güvenlik bulunmaktadır.",
      price: 9500000,
      city: "İstanbul",
      district: "Kadıköy",
      neighborhood: "Moda",
      address: "Moda Caddesi No: 45",
      propertyType: "daire",
      listingType: "sale",
      squareMeters: 145,
      rooms: "3+1",
      bathrooms: 2,
      buildingAge: 5,
      floor: 7,
      totalFloors: 12,
      furnished: false,
      insideComplex: true,
      mortgageEligible: true,
      featured: true,
      approved: true,
      agentId: agent1.id,
    },
    {
      title: "Beşiktaş Levent'te Boğaz Manzaralı Lüks Daire",
      description: "Beşiktaş'ın en prestijli lokasyonunda, eşsiz Boğaz manzarasına sahip, lüks dizayn edilmiş 4+1 daire. Akıllı ev sistemi, yerden ısıtma, merkezi klima. 7/24 güvenlik, kapalı otopark, yüzme havuzu.",
      price: 22000000,
      city: "İstanbul",
      district: "Beşiktaş",
      neighborhood: "Levent",
      address: "Nispetiye Caddesi No: 120",
      propertyType: "daire",
      listingType: "sale",
      squareMeters: 220,
      rooms: "4+1",
      bathrooms: 3,
      buildingAge: 2,
      floor: 15,
      totalFloors: 25,
      furnished: true,
      insideComplex: true,
      mortgageEligible: true,
      featured: true,
      approved: true,
      agentId: agent1.id,
    },
    {
      title: "Sarıyer Tarabya'da Boğaz Manzaralı Villa",
      description: "Sarıyer Tarabya'da, özel havuzlu, 600 m² bahçeli, müstakil Boğaz manzaralı villa. 5 yatak odası, 4 banyo, geniş oturma salonu. Vapur iskelesine 10 dakika mesafede.",
      price: 45000000,
      city: "İstanbul",
      district: "Sarıyer",
      neighborhood: "Tarabya",
      propertyType: "villa",
      listingType: "sale",
      squareMeters: 450,
      rooms: "5+2",
      bathrooms: 4,
      buildingAge: 3,
      floor: 1,
      totalFloors: 2,
      furnished: true,
      insideComplex: false,
      mortgageEligible: false,
      featured: true,
      approved: true,
      agentId: agent2.id,
    },
    {
      title: "Şişli Nişantaşı'nda Kiralık 2+1 Daire",
      description: "Nişantaşı'nın kalbinde, alışveriş ve restoranlarına yakın, tam eşyalı kiralık 2+1 daire. Yeni bina, modern iç tasarım, klimalı.",
      price: 45000,
      city: "İstanbul",
      district: "Şişli",
      neighborhood: "Nişantaşı",
      propertyType: "daire",
      listingType: "rent",
      squareMeters: 90,
      rooms: "2+1",
      bathrooms: 1,
      buildingAge: 4,
      floor: 5,
      totalFloors: 10,
      furnished: true,
      insideComplex: true,
      mortgageEligible: false,
      featured: false,
      approved: true,
      agentId: agent1.id,
    },
    {
      title: "Üsküdar Kuzguncuk'ta Tarihi Manzaralı Daire",
      description: "Üsküdar Kuzguncuk'ta, Tarihi Yarımada ve Kız Kulesi manzaralı, bakımlı 2+1 daire. Sessiz ve huzurlu mahallede, yeşil alana yakın konumda.",
      price: 7800000,
      city: "İstanbul",
      district: "Üsküdar",
      neighborhood: "Kuzguncuk",
      propertyType: "daire",
      listingType: "sale",
      squareMeters: 110,
      rooms: "2+1",
      bathrooms: 1,
      buildingAge: 12,
      floor: 3,
      totalFloors: 5,
      furnished: false,
      insideComplex: false,
      mortgageEligible: true,
      featured: true,
      approved: true,
      agentId: agent2.id,
    },
    {
      title: "Beylikdüzü'nde Yeni Binada Kiralık 3+1",
      description: "Beylikdüzü'nün gelişen bölgesinde, metrobüse yakın, yeni binada kiralık 3+1 daire. Site içi sosyal tesisler, kapalı otopark, 7/24 güvenlik.",
      price: 28000,
      city: "İstanbul",
      district: "Beylikdüzü",
      neighborhood: "Adnan Kahveci",
      propertyType: "daire",
      listingType: "rent",
      squareMeters: 130,
      rooms: "3+1",
      bathrooms: 2,
      buildingAge: 1,
      floor: 8,
      totalFloors: 18,
      furnished: false,
      insideComplex: true,
      mortgageEligible: false,
      featured: false,
      approved: true,
      agentId: agent1.id,
    },
    {
      title: "Ataşehir'de Satılık Yatırımlık Daire",
      description: "İstanbul Finans Merkezi'ne yakın, Ataşehir'de yüksek kira getirili 1+1 daire. Rezidans konseptli bina, ticari katlar dahil. Yatırım amaçlı ideal fırsat.",
      price: 5500000,
      city: "İstanbul",
      district: "Ataşehir",
      neighborhood: "Barbaros",
      propertyType: "daire",
      listingType: "sale",
      squareMeters: 65,
      rooms: "1+1",
      bathrooms: 1,
      buildingAge: 3,
      floor: 20,
      totalFloors: 35,
      furnished: true,
      insideComplex: true,
      mortgageEligible: true,
      featured: false,
      approved: true,
      agentId: agent2.id,
    },
    {
      title: "Başakşehir'de Satılık 4+1 Geniş Daire",
      description: "Başakşehir'in modern konut projesinde, geniş 4+1 daire. Büyük bahçeli site, çocuk parkı, yüzme havuzu. Kanal İstanbul bölgesine yakın yatırım fırsatı.",
      price: 8200000,
      city: "İstanbul",
      district: "Başakşehir",
      neighborhood: "Kayaşehir",
      propertyType: "daire",
      listingType: "sale",
      squareMeters: 195,
      rooms: "4+1",
      bathrooms: 2,
      buildingAge: 2,
      floor: 5,
      totalFloors: 14,
      furnished: false,
      insideComplex: true,
      mortgageEligible: true,
      featured: true,
      approved: true,
      agentId: agent2.id,
    },
  ];

  for (const propData of propertyData) {
    const prop = await storage.createProperty(propData);
    await storage.addPropertyImage({
      propertyId: prop.id,
      imageUrl: `https://picsum.photos/seed/prop${prop.id}/800/600`,
      isPrimary: true,
    });
  }

  await storage.createBlogPost({
    title: "İstanbul'da Ev Fiyatları 2026: Bölge Bölge Analiz",
    content: "İstanbul emlak piyasası 2026 yılında da hareketliliğini sürdürmektedir. Özellikle Kadıköy, Beşiktaş ve Sarıyer bölgelerinde fiyatlar artmaya devam ederken, Beylikdüzü ve Başakşehir gibi gelişen semtlerde uygun fiyatlı seçenekler bulunmaktadır.\n\nBoğaz manzaralı dairelerde m² fiyatları 80.000-150.000 TL aralığına ulaşırken, Anadolu Yakası'nda Kadıköy ve Üsküdar gibi merkezi ilçelerde 60.000-90.000 TL bandında seyretmektedir. Beylikdüzü ve Esenyurt gibi dış hatlarda ise 25.000-45.000 TL ile daha ekonomik seçenekler mevcuttur.\n\nYatırım perspektifinden değerlendirildiğinde, metro hattı güzergâhları ve kentsel dönüşüm projeleri yakınındaki taşınmazlar en yüksek değer artışını yaşayan bölgeler arasında yer almaktadır.",
    slug: "istanbul-ev-fiyatlari-2026",
    seoTitle: "İstanbul Ev Fiyatları 2026 - Bölge Bölge Analiz",
    seoDescription: "İstanbul'da 2026 yılı ev fiyatları, bölge bölge detaylı analiz. Kadıköy, Beşiktaş, Sarıyer, Beylikdüzü emlak fiyatları.",
    published: true,
    authorId: admin.id,
  });

  await storage.createBlogPost({
    title: "İstanbul'da Yatırım İçin En İyi Semtler",
    content: "İstanbul, dünyanın en dinamik gayrimenkul piyasalarından birini barındırmaktadır. Yatırım kararı verirken konumun önemi tartışılmazdır.\n\nAvrupa Yakası'nda Beşiktaş, Şişli ve Sarıyer; prestij ve değer artışı açısından öne çıkarken Kağıthane, Gaziosmanpaşa ve Arnavutköy kentsel dönüşüm potansiyeliyle dikkat çekmektedir. Anadolu Yakası'nda ise Kadıköy, Üsküdar ve Ataşehir değer koruyan tercihler arasındadır.\n\nKanal İstanbul projesi güzergâhındaki Başakşehir, Arnavutköy ve Büyükçekmece bölgeleri uzun vadeli yatırım için cazip fırsatlar sunmaya devam etmektedir.",
    slug: "istanbul-yatirim-icin-en-iyi-semtler",
    seoTitle: "İstanbul'da Yatırım İçin En İyi Semtler 2026",
    seoDescription: "İstanbul'da gayrimenkul yatırımı için en iyi semtler. Bölge bazlı analiz ve fiyat değerlendirmeleri.",
    published: true,
    authorId: admin.id,
  });

  await storage.createTeamMember({
    name: "Ahmet Yılmaz",
    title: "Kıdemli Emlak Danışmanı",
    phone: "+90 549 449 23 36",
    email: "ahmet@mirhanestate.com",
    description: "15 yıllık tecrübesiyle İstanbul'da Beşiktaş, Sarıyer ve Kadıköy bölgelerinde lüks konut satışında uzmanlaşmıştır. Boğaz manzaralı villa ve rezidans projeleri konusunda derin bilgiye sahiptir.",
    specialty: ["Konut", "Villa", "Yabancı Müşteri"],
    experience: 15,
    languages: ["Türkçe", "İngilizce", "Rusça"],
    rating: "4.9",
    reviewCount: 87,
    sortOrder: 1,
    active: true,
  });

  await storage.createTeamMember({
    name: "Elif Kaya",
    title: "Emlak Danışmanı",
    phone: "+90 549 449 23 36",
    email: "elif@mirhanestate.com",
    description: "Beşiktaş, Kadıköy ve Sarıyer bölgelerinde lüks konut satışında uzmanlaşmıştır. Yabancı yatırımcılara Türkiye'de gayrimenkul edinimi konusunda kapsamlı danışmanlık sunmaktadır.",
    specialty: ["Konut", "Yabancı Müşteri"],
    experience: 8,
    languages: ["Türkçe", "İngilizce", "Arapça"],
    rating: "4.8",
    reviewCount: 54,
    sortOrder: 2,
    active: true,
  });

  await storage.createTeamMember({
    name: "Murat Demir",
    title: "Ticari Gayrimenkul Uzmanı",
    phone: "+90 549 449 23 36",
    email: "murat@mirhanestate.com",
    description: "Şişli, Levent ve Maslak bölgelerinde ofis ve ticari gayrimenkul danışmanlığı yapmaktadır. İstanbul Finans Merkezi projelerinde uzman rehberlik sunmaktadır.",
    specialty: ["Ticari Gayrimenkul", "Konut"],
    experience: 12,
    languages: ["Türkçe", "İngilizce"],
    rating: "4.7",
    reviewCount: 41,
    sortOrder: 3,
    active: true,
  });

  await storage.createTeamMember({
    name: "Selin Arslan",
    title: "Kiralık Konut Uzmanı",
    phone: "+90 549 449 23 36",
    email: "selin@mirhanestate.com",
    description: "Avrupa ve Anadolu Yakası'nda kiralık daire ve rezidans konusunda uzmanlaşmıştır. Öğrenci ve genç profesyonellere uygun çözümler üretmektedir.",
    specialty: ["Konut"],
    experience: 5,
    languages: ["Türkçe", "Almanca"],
    rating: "4.6",
    reviewCount: 29,
    sortOrder: 4,
    active: true,
  });

  await storage.createTeamMember({
    name: "Kemal Şahin",
    title: "Arsa ve Yatırım Danışmanı",
    phone: "+90 549 449 23 36",
    email: "kemal@mirhanestate.com",
    description: "İstanbul'un gelişen bölgelerinde arsa ve yatırım amaçlı gayrimenkul danışmanlığı yapmaktadır. Kentsel dönüşüm projeleri konusunda deneyimlidir.",
    specialty: ["Arsa", "Konut"],
    experience: 10,
    languages: ["Türkçe", "İngilizce"],
    rating: "4.8",
    reviewCount: 63,
    sortOrder: 5,
    active: true,
  });
}
